added a change

diff --git a/.github/workflows/app_check.yml b/.github/workflows/app_check.yml
--- a/.github/workflows/app_check.yml
+++ b/.github/workflows/app_check.yml
@@ -1,3 +1,56 @@
+# # .github/workflows/ci.yml
+
+# name: Flask App CI
+
+# on:
+#   pull_request:
+#     branches:
+#       - main
+
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       # Checkout the code
+#       - name: Checkout code
+#         uses: actions/checkout@v2
+
+#       # Set up Python
+#       - name: Set up Python 3.9
+#         uses: actions/setup-python@v2
+#         with:
+#           python-version: 3.9
+
+#       # Install dependencies from requirements.txt if it exists
+#       - name: Install dependencies
+#         run: |
+#           ls -r
+#           python -m pip install --upgrade pip
+#           if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
+
+#       # Set up the virtual environment and navigate to the app directory
+#       - name: Set up Virtual Environment and Navigate
+#         run: |
+#           pip install -r requirement.txt
+#           python -m venv venv
+
+#       - name: Check Health API Test Output for Errors
+#         run: |
+#           python -m unittest discover -s tests -p 'test_healthcheck.py' 2> tee user_output.log
+#           if grep -i 'AssertionError' user_output.log; then
+#             echo 'Test failed due to an error or failure!'
+#             exit 1
+#           fi
+
+#       - name: Check User API Test Output for Errors
+#         run: |
+#           python -m unittest discover -s app/tests -p 'test_user.py' 2> tee user_output.log
+#           if grep -i 'AssertionError' user_output.log; then
+#             echo 'Test failed due to an error or failure!'
+#             exit 1
+#           fi
+
 # .github/workflows/ci.yml
 
 name: Flask App CI
@@ -26,7 +79,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          if [ -f requirements.txt ]; then pip install -r requirement.txt; fi
+          if [ -f requirement.txt ]; then pip install -r requirement.txt; fi
 
       # Create a .env file with required environment variables
       - name: Create .env file
