added a change

diff --git a/.github/workflows/app_check.yml b/.github/workflows/app_check.yml
--- a/.github/workflows/app_check.yml
+++ b/.github/workflows/app_check.yml
@@ -50,9 +50,11 @@ jobs:
       - name: Check Health Check Test Output for Errors
         run: |
           python -m unittest discover -s app/tests -p "test_healthcheck.py" | tee test_output.log
+          echo "HERE"
+          cat test_output.log
           if grep -E "FAIL|ERROR|Traceback" test_output.log; then
-          echo "Test failed due to an error or failure!"
-          exit 1
+            echo "Test failed due to an error or failure!"
+            exit 1
           fi
 
       # Search for "error" in user API test output log and fail if found
@@ -60,6 +62,6 @@ jobs:
         run: |
           python -m unittest discover -s app/tests -p "test_user.py" | tee test_output.log
           if grep -E "FAIL|ERROR|Traceback" test_output.log; then
-          echo "Test failed due to an error or failure!"
-          exit 1
+            echo "Test failed due to an error or failure!"
+            exit 1
           fi
